export const PROFILE_DETAILS_REQUEST = 'PROFILE_DETAILS_REQUEST'
export const PROFILE_DETAILS_SUCCESS = 'PROFILE_DETAILS_SUCCESS'
export const PROFILE_DETAILS_FAIL = 'PROFILE_DETAILS_FAIL'
export const PROFILE_DETAILS_RESET = 'PROFILE_DETAILS_RESET'


export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST'
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL'
export const PROFILE_UPDATE_RESET = 'PROFILE_UPDATE_RESET'

export const PROFILE_DETAILS_EMPLOYEE_REQUEST = 'PROFILE_DETAILS_EMPLOYEE_REQUEST'
export const PROFILE_DETAILS_EMPLOYEE_SUCCESS = 'PROFILE_DETAILS_EMPLOYEE_SUCCESS'
export const PROFILE_DETAILS_EMPLOYEE_FAIL = 'PROFILE_DETAILS_EMPLOYEE_FAIL'
export const PROFILE_DETAILS_EMPLOYEE_RESET = 'PROFILE_DETAILS_EMPLOYEE_RESET'

export const PROFILE_CREATE_REQUEST = 'PROFILE_CREATE_REQUEST'
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS'
export const PROFILE_CREATE_FAIL = 'PROFILE_CREATE_FAIL'
export const PROFILE_CREATE_RESET = 'PROFILE_CREATE_RESET'

export const PROFILE_CREATE_EMPLOYEE_REQUEST = 'PROFILE_CREATE_EMPLOYEE_REQUEST'
export const PROFILE_CREATE_EMPLOYEE_SUCCESS = 'PROFILE_CREATE_EMPLOYEE_SUCCESS'
export const PROFILE_CREATE_EMPLOYEE_FAIL = 'PROFILE_CREATE_EMPLOYEE_FAIL'
export const PROFILE_CREATE_EMPLOYEE_RESET = 'PROFILE_CREATE_EMPLOYEE_RESET'